version: '3.7'
services:

  web:
    image: parser
    command: python manage.py runserver 0.0.0.0:8000 & python manage.py makemigrations & python manage.py migrate
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=scraper_user
      - POSTGRES_PASSWORD=scraper_password
      - POSTGRES_DB=scraper_db

  redis:
    image: redis

  celery:
    image: parser
    command: celery -A api_scraper worker -l info
    depends_on:
      - redis

  celery-beat:
    image: parser
    command: celery -A api_scraper beat -l info
    depends_on:
      - redis

  tg-bot:
    image: tg_bot
    working_dir: /tg_bot
    command: sh -c "python3 tg_bot.py"
    depends_on:
      - web
    expose:
      - 8000
    network_mode: host

volumes:
  postgres_data: